### ISSUE TITLE
[BUG] Failed to read filenames with weird characters

### ISSUE THREAD

**Issue by dnth** [visual-layer/fastdup#116]
I ran `fd.vis.duplicates_gallery()` and got an error

```bash
25%|██▌       | 5/20 [00:00<00:01, 14.14it/s]Traceback (most recent call last):
  File "/home/dnth/anaconda3/envs/fastdupv1/lib/python3.10/site-packages/fastdup/galleries.py", line 361, in do_create_duplicates_gallery
    img, imgpath = create_triplet_img(row, work_dir, save_dir, extract_filenames, get_bounding_box_func,
  File "/home/dnth/anaconda3/envs/fastdupv1/lib/python3.10/site-packages/fastdup/image.py", line 275, in create_triplet_img
    assert img1 is not None, f"Failed to read image1 {img1_path} {str(input_dir)}"
AssertionError: Failed to read image1 images/architecure/32_Contraforts_de_l''església_del_Rosari_al_carrer_de_Mallorca_(l''Alguer).jpg images
100%|██████████| 20/20 [00:00<00:00, 43.45it/s]
Failed to read image from img_path images/architecure/32_Contraforts_de_l''església_del_Rosari_al_carrer_de_Mallorca_(l''Alguer).jpg
Failed to read image from img_path images/architecure/32_Contraforts_de_l''esgl�sia_del_Rosari_al_carrer_de_Mallorca_(l''Alguer).jpg
Failed to generate viz for images 3945 3946 Failed to read image1 images/architecure/32_Contraforts_de_l''església_del_Rosari_al_carrer_de_Mallorca_(l''Alguer).jpg images
Stored similarity visual view in  fastdup_report/galleries/duplicates.html
```

It failed to read the file with weird characters in it. 

I tried changing the file name to `test.img` and it works again.

Here's my notebook 

https://github.com/dnth/clean-up-digital-life-fastdup-blogpost/blob/main/fastdup_analyze.ipynb

**Comment by dbickson** [comment]
Should be fixed in 0.905 please check
