### ISSUE TITLE
[Bug]: fastdup does not handle relative paths ~/ correctly

### ISSUE THREAD

**Issue by dbickson** [visual-layer/fastdup#228]
### What happened?

    img = fastdup_imread(f, input_dir, kwargs)
  File "/Users/dannybickson/Documents/visual_database/cxx/fastdup/image.py", line 150, in fastdup_imread
    assert os.path.exists(input_dir), "Failed to find input_dir: " + input_dir
AssertionError: Failed to find input_dir: ~/Downloads/farm_insects
Failed on component ['/Users/dannybickson/Downloads/farm_insects/Corn Earworms/Image_68.jpg', 904, '~/Downloads/farm_insects', None, {'save_artifacts': False, 'id_to_filename_func': <function FastdupVisualizer._get_filneme_func.<locals>.get_filename_func at 0x131755c10>, 'jupyter_html': False, 'load_crops': False, 'draw_bbox': False, 'sort_by': 'comp_size', 'lazy_load': False, 'run_hierarchical': False, 'selection_strategy': 0, 'input_dir': '~/Downloads/farm_insects'}] Failed to read all images
Traceback (most recent call last):
  File "/Users/dannybickson/Documents/visual_database/cxx/fastdup/galleries.py", line 886, in visualize_top_components
    assert len(tmp_images),"Failed to read all images"
AssertionError: Failed to read all images

### What version of fastdup were you runnning on?

1.23

### What version of Python were you running on?

Python 3.8

### Operating System

MacOSX 12.6.1

**Comment by dbickson** [comment]
Fixed in 1.24
