### ISSUE TITLE
[Bug]: Kernel keep crashing when trying to run fd.run()

### ISSUE THREAD

**Issue by segalinc** [visual-layer/fastdup#317]
### What happened?

 Trying to run a demo using Huggingdaface dataset

Error:
`The Kernel crashed while executing code in the current cell or a previous cell. 
Please review the code in the cell(s) to identify a possible cause of the failure. 
Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. 
View Jupyter [log](command:jupyter.viewOutput) for further details.`

in the log it show it's not able to load onxx models
I also tried with DInoV2 but I get the same issue

I tried both on a terminal and jupiter. On terminal I get segmentation fault

### What did you expect to see?

The algorithm running as in the demos

### What version of fastdup were you runnning on?

1.85

### What version of Python were you running on?

Python 3.10

### Operating System

Ubuntut

### Reproduction steps

```
import fastdup
from fastdup.datasets import FastdupHFDataset
dataset = FastdupHFDataset("andrewburns/anime_sprites_v1", split="train", img_key='image', label_key='text')
fd = fastdup.create(input_dir=dataset.img_dir, work_dir='data/fastdup_work_dir') #or dir with images
fd.run(annotations=dataset.annotations, verbose=True)
```

### Relevant log output

FastDup Software, (C) copyright 2022 Dr. Amir Alush and Dr. Danny Bickson.
2024-02-24 19:05:38 [FATAL] Failed to initialize ort model [/root/miniforge3/envs/animedm/lib/python3.10/site-packages/fastdup/UndisclosedFastdupModel.ort](https://vscode-remote+ssh-002dremote-002bwb2a10.vscode-resource.vscode-cdn.net/root/miniforge3/envs/animedm/lib/python3.10/site-packages/fastdup/UndisclosedFastdupModel.ort) with error [/mnt/data/onnxruntime/onnxruntime/core/platform/posix/env.cc:183](https://vscode-remote+ssh-002dremote-002bwb2a10.vscode-resource.vscode-cdn.net/mnt/data/onnxruntime/onnxruntime/core/platform/posix/env.cc:183) onnxruntime::{anonymous}::PosixThread::PosixThread(const char*, int, unsigned int (*)(int, Eigen::ThreadPoolInterface*), Eigen::ThreadPoolInterface*, const onnxruntime::ThreadOptions&) pthread_setaffinity_np failed, error code: 2 error msg: No such file or directory

2024-02-24 19:05:38 [ERROR] Failed to initialize ORT

### Attach a screenshot [Optional]

![image](https://github.com/visual-layer/fastdup/assets/9353106/2e6cb9c9-4c27-4f0e-9d9e-d70b989ba606)

### Contact Details [Optional]

segalin.cristina@gmail.com

**Comment by dbickson** [comment]
Hello @segalinc thanks for reaching out to fastdup support. It seems Jupyter swallows the error message so it is hard to know why there was a crash. 
Can you please run the same code on a python terminal / ipython terminal and share here the output you see before the crash? In addition please upgrade fastdup to the latest version using pip3 install -U fastdup.
Thanks

**Comment by segalinc** [comment]
Hello,
I already have the latest version 1.85

this is the error I get  running in terminal

```
fd = fastdup.create(input_dir=dataset.img_dir, work_dir='data/fastdup_work_dir') #or dir with images
>>> fd.run(annotations=dataset.annotations, verbose=True)
FastDup Software, (C) copyright 2022 Dr. Amir Alush and Dr. Danny Bickson.
2024-02-25 04:29:19 [INFO] Version 1.85 Release compiled on Jan 16 2024 09:35:44
2024-02-25 04:29:19 [FATAL] Failed to initialize ort model /root/miniforge3/envs/animedm/lib/python3.10/site-packages/fastdup/UndisclosedFastdupModel.ort with error /mnt/data/onnxruntime/onnxruntime/core/platform/posix/env.cc:183 onnxruntime::{anonymous}::PosixThread::PosixThread(const char*, int, unsigned int (*)(int, Eigen::ThreadPoolInterface*), Eigen::ThreadPoolInterface*, const onnxruntime::ThreadOptions&) pthread_setaffinity_np failed, error code: 2 error msg: No such file or directory

2024-02-25 04:29:19 [ERROR] Failed to initialize ORT
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniforge3/envs/animedm/lib/python3.10/site-packages/fastdup/engine.py", line 157, in run
    return super().run(annotations=annotations, input_dir=input_dir, subset=subset, data_type=data_type,
  File "/root/miniforge3/envs/animedm/lib/python3.10/site-packages/fastdup/sentry.py", line 144, in inner_function
    raise ex
  File "/root/miniforge3/envs/animedm/lib/python3.10/site-packages/fastdup/sentry.py", line 135, in inner_function
    ret = func(*args, **kwargs)
  File "/root/miniforge3/envs/animedm/lib/python3.10/site-packages/fastdup/fastdup_controller.py", line 584, in run
    raise RuntimeError('Fastdup execution failed')
RuntimeError: Fastdup execution failed
>>> Segmentation fault

```

**Comment by dbickson** [comment]
Can you verify this path exists? 
/root/miniforge3/envs/animedm/lib/python3.10/site-packages/fastdup/UndisclosedFastdupModel.ort

**Comment by dbickson** [comment]
Hi @segalinc I see this failed:
<img width="925" alt="Screen Shot 2024-02-25 at 6 34 53" src="https://github.com/visual-layer/fastdup/assets/4495523/ed03da5d-bbe2-4913-9922-1dfd9c028b13">
It seems microsoft onnx functionality of setting the number of threads is somehow not supported on your system.
What is your os and which hardware are you running on?

**Comment by segalinc** [comment]
It does

**Comment by segalinc** [comment]
I'm on Ubuntu

**Comment by dbickson** [comment]
I suspect you are on ubuntu 18 I suggest to upgrade the instance to 20 or 22.
Can you check using 
cat /etc/os-release | grep VERSION_ID

**Comment by segalinc** [comment]
yes I am on ubuntu 18 but I can't upgrade I don't have control of the version

**Comment by dbickson** [comment]
fastdup works fine on ubuntu 18.. I suspect you have an older flavor of ubuntu 18.
We work fine on 18.04

**Comment by segalinc** [comment]
I have 18.04

**Comment by segalinc** [comment]
the error happens even if I change the model

**Comment by dbickson** [comment]
This error will happen for all models since it is an operating system issue, can you check your kernel version using
`uname -r`

**Comment by segalinc** [comment]
I also tried with a local model

```
fd.run(model_path='./dinov2_vits14.onnx', annotations=dataset.annotations, verbose=True, d=384)
FastDup Software, (C) copyright 2022 Dr. Amir Alush and Dr. Danny Bickson.
2024-02-25 04:52:58 [INFO] Version 1.85 Release compiled on Jan 16 2024 09:35:44
2024-02-25 04:52:59 [FATAL] Failed to initialize ort model ./dinov2_vits14.onnx with error /mnt/data/onnxruntime/onnxruntime/core/platform/posix/env.cc:183 onnxruntime::{anonymous}::PosixThread::PosixThread(const char*, int, unsigned int (*)(int, Eigen::ThreadPoolInterface*), Eigen::ThreadPoolInterface*, const onnxruntime::ThreadOptions&) pthread_setaffinity_np failed, error code: 2 error msg: No such file or directory

2024-02-25 04:52:59 [ERROR] Failed to initialize ORT
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniforge3/envs/animedm/lib/python3.10/site-packages/fastdup/engine.py", line 157, in run
    return super().run(annotations=annotations, input_dir=input_dir, subset=subset, data_type=data_type,
  File "/root/miniforge3/envs/animedm/lib/python3.10/site-packages/fastdup/sentry.py", line 144, in inner_function
    raise ex
  File "/root/miniforge3/envs/animedm/lib/python3.10/site-packages/fastdup/sentry.py", line 135, in inner_function
Segmentation fault
```

**Comment by segalinc** [comment]
5.15.134netflix-g795dc0d5168f

**Comment by dbickson** [comment]
Our kernel version which works fine is 5.4.0-1106-gcp
Your kernel is 5.15.134, need to check why pthread_setaffinity_np fails..

**Comment by dbickson** [comment]
I suggest contacting your admins asking for a newer OS build...

**Comment by segalinc** [comment]
could this be related? https://github.com/microsoft/onnxruntime/issues/10113 ?
Admins won't change the build of a company for this eheh

**Comment by segalinc** [comment]
I tried something and this is what I got

```
>>> import onnxruntime
>>> onnxruntime.InferenceSession("dinov2_vits14.onnx")
2024-02-25 05:13:52.685580921 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349128, index: 0, mask: {0, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.685752673 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349130, index: 2, mask: {1, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.685855664 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349132, index: 4, mask: {2, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.685980576 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349134, index: 6, mask: {3, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.686135718 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349136, index: 8, mask: {4, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.686207999 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349138, index: 10, mask: {5, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.686326860 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349140, index: 12, mask: {6, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.686427871 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349142, index: 14, mask: {7, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.686566383 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349144, index: 16, mask: {8, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.686662324 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349146, index: 18, mask: {9, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.686780725 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349148, index: 20, mask: {10, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.686915507 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349150, index: 22, mask: {11, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.687007318 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349152, index: 24, mask: {12, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.687112709 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349154, index: 26, mask: {13, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.687210470 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349156, index: 28, mask: {14, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.687316701 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349158, index: 30, mask: {15, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.687412752 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349160, index: 32, mask: {16, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.687519934 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349162, index: 34, mask: {17, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.687646225 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349164, index: 36, mask: {18, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.687801807 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349166, index: 38, mask: {19, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.687892548 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349168, index: 40, mask: {20, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.687994269 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349170, index: 42, mask: {21, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.688087520 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349172, index: 44, mask: {22, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.688176901 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349174, index: 46, mask: {23, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.688277643 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349176, index: 48, mask: {24, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.688363384 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349178, index: 50, mask: {25, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.688477245 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349180, index: 52, mask: {26, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.688589806 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349182, index: 54, mask: {27, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.688693007 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349184, index: 56, mask: {28, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.688792769 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349186, index: 58, mask: {29, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.688898040 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349188, index: 60, mask: {30, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.688983781 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349190, index: 62, mask: {31, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.689125972 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349192, index: 64, mask: {32, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.689264584 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349194, index: 66, mask: {33, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.689385705 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349196, index: 68, mask: {34, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.689517587 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349198, index: 70, mask: {35, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.689626078 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349200, index: 72, mask: {36, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.689740439 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349202, index: 74, mask: {37, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.689840311 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349204, index: 76, mask: {38, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.689945892 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349206, index: 78, mask: {39, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.690085773 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349208, index: 80, mask: {40, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.690216565 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349210, index: 82, mask: {41, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.690313866 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349212, index: 84, mask: {42, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.690423507 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349214, index: 86, mask: {43, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.690571989 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349216, index: 88, mask: {44, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.690684870 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349218, index: 90, mask: {45, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.690805822 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349220, index: 92, mask: {46, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
2024-02-25 05:13:52.690912723 [E:onnxruntime:Default, env.cc:254 ThreadMain] pthread_setaffinity_np failed for thread: 1349222, index: 94, mask: {47, }, error code: 22 error msg: Invalid argument. Specify the number of threads explicitly so the affinity is not set.
<onnxruntime.capi.onnxruntime_inference_collection.InferenceSession object at 0x7f0d2c8194b0>```

**Comment by segalinc** [comment]
```
 pip install fastdup
Looking in indexes: https://pypi.XXXXXXX/simple
Requirement already satisfied: fastdup in /root/miniforge3/envs/animedm/lib/python3.10/site-packages (1.85)
Requirement already satisfied: pandas in /root/miniforge3/envs/animedm/lib/python3.10/site-packages (from fastdup) (2.2.1)
Requirement already satisfied: numpy in /root/miniforge3/envs/animedm/lib/python3.10/site-packages (from fastdup) (1.24.0)
Requirement already satisfied: tqdm in /root/miniforge3/envs/animedm/lib/python3.10/site-packages (from fastdup) (4.66.2)
Requirement already satisfied: pyyaml in /root/miniforge3/envs/animedm/lib/python3.10/site-packages (from fastdup) (6.0.1)
Requirement already satisfied: pillow-heif in /root/miniforge3/envs/animedm/lib/python3.10/site-packages (from fastdup) (0.15.0)
Collecting requests==2.28.1 (from fastdup)
  Using cached https://pypi.XXXXX/packages/848393/requests-2.28.1-py3-none-any.whl (62 kB)
Requirement already satisfied: packaging in /root/miniforge3/envs/animedm/lib/python3.10/site-packages (from fastdup) (23.2)
Requirement already satisfied: sentry-sdk in /root/miniforge3/envs/animedm/lib/python3.10/site-packages (from fastdup) (1.40.5)
Requirement already satisfied: pillow in /root/miniforge3/envs/animedm/lib/python3.10/site-packages (from fastdup) (10.2.0)
Requirement already satisfied: opencv-python-headless in /root/miniforge3/envs/animedm/lib/python3.10/site-packages (from fastdup) (4.9.0.80)
Requirement already satisfied: charset-normalizer<3,>=2 in /root/miniforge3/envs/animedm/lib/python3.10/site-packages (from requests==2.28.1->fastdup) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /root/miniforge3/envs/animedm/lib/python3.10/site-packages (from requests==2.28.1->fastdup) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /root/miniforge3/envs/animedm/lib/python3.10/site-packages (from requests==2.28.1->fastdup) (1.26.13)
Requirement already satisfied: certifi>=2017.4.17 in /root/miniforge3/envs/animedm/lib/python3.10/site-packages (from requests==2.28.1->fastdup) (2022.12.7)

Requirement already satisfied: python-dateutil>=2.8.2 in /root/miniforge3/envs/animedm/lib/python3.10/site-packages (from pandas->fastdup) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /root/miniforge3/envs/animedm/lib/python3.10/site-packages (from pandas->fastdup) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /root/miniforge3/envs/animedm/lib/python3.10/site-packages (from pandas->fastdup) (2024.1)
Requirement already satisfied: six>=1.5 in /root/miniforge3/envs/animedm/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas->fastdup) (1.16.0)
Installing collected packages: requests
  Attempting uninstall: requests
    Found existing installation: requests 2.31.0
    Uninstalling requests-2.31.0:
      Successfully uninstalled requests-2.31.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
renumics-spotlight 1.6.6 requires requests>=2.31, but you have requests 2.28.1 which is incompatible.
Successfully installed requests-2.28.1

```

**Comment by dbickson** [comment]
Hi @segalinc we can try to compile a version for ubuntu 18 which avoids setting up the threads in ONNX, however it may require your patience to test it...

**Comment by segalinc** [comment]
Thank you!!
I created a ticket with the infra team and see if they can help on this
before I ask you to go down and do so much work
Can we keep it open until I get some reply from them?

**Comment by dbickson** [comment]
HI @segalinc I found the issue, I suddenly remembered this one: https://github.com/visual-layer/fastdup/issues/300.
Onnxruntime is trying to set the affinity of a thread into a specific cpu, this failed in issue 300 on docker virtualization, I believe your ubuntu machine may be a kubernetis node running within docker. We have compiled v 1.100 for Ubutnu 18 skipping setting the affinity. Please try it out and let us know if this works.

**Comment by segalinc** [comment]
I gave it a try
when running I get
`Error: failed to set cpu affinity error code 2 No such file or directory` multiple times but then it seems working (i added verbose=True)
Thanks so much for digging into this
Very excited to use the library now !

**Comment by segalinc** [comment]
Thanks to you for helping me out
Really appreciated
