### ISSUE TITLE
Can't install Fastdup using Poetry

### ISSUE THREAD

**Issue by kikohs** [visual-layer/fastdup#51]
Hi, I'm trying to install your package with [Poetry (package manager)](https://github.com/python-poetry/poetry) on WSL (ubuntu) with Python3.8 but it fails :(.

I tried the regular way: `poetry add fastdup`

```
  • Installing fastdup (0.180): Failed

  RuntimeError

  Unable to find installation candidates for fastdup (0.180)
```

This is what I get when I tried to add from git directly

`poetry add git+https://github.com/visual-layer/fastdup.git#main`

Please let me know if there is something I can do.
Thanks.

```
Unable to determine package info for path: /home/kikohs/.cache/pypoetry/virtualenvs/rts-DIiCth0j-py3.8/src/fastdup

Command ['/tmp/tmpzgduc58e/.venv/bin/python', '-'] errored with the following return code 1, and output: 
Traceback (most recent call last):
  File "<stdin>", line 9, in <module>
  File "/tmp/tmpzgduc58e/.venv/lib/python3.8/site-packages/build/__init__.py", line 208, in __init__
    _validate_source_directory(srcdir)
  File "/tmp/tmpzgduc58e/.venv/lib/python3.8/site-packages/build/__init__.py", line 109, in _validate_source_directory
    raise BuildException(f'Source {srcdir} does not appear to be a Python project: no pyproject.toml or setup.py')
build.BuildException: Source /home/kikohs/.cache/pypoetry/virtualenvs/rts-DIiCth0j-py3.8/src/fastdup does not appear to be a Python project: no pyproject.toml or setup.py
input was : import build
import build.env
import pep517

source = '/home/kikohs/.cache/pypoetry/virtualenvs/rts-DIiCth0j-py3.8/src/fastdup'
dest = '/tmp/tmpzgduc58e/dist'

with build.env.IsolatedEnvBuilder() as env:
    builder = build.ProjectBuilder(
        srcdir=source,
        scripts_dir=env.scripts_dir,
        python_executable=env.executable,
        runner=pep517.quiet_subprocess_runner,
    )
    env.install(builder.build_system_requires)
    env.install(builder.get_requires_for_build('wheel'))
    builder.metadata_path(dest)

No fallback setup.py file was found to generate egg_info.
```

**Comment by dbickson** [comment]
Hi @kikohs thanks for trying us on windows! We would love to help. We never used poetry before. Can you try and install inside the WSL terminal
```
python3.8 -m pip install -U pip
python3.8 -m pip install fastdup
```

And let us know if this works?

**Comment by kikohs** [comment]
It works! This is how I use it as a fallback but it doesn't get versionned so it is less portable as an install (you need a post-init script) manually triggered by the user.

**Comment by dbickson** [comment]
We will take a look into poetry to see how difficult it is to support.
Thanks for your feedback, feel free to reach out for any issues!

**Comment by jdonini** [comment]
Hi, @dbickson, do you have any updates on how to install correctly using Poetry?

I tried to install it using Poetry and encountered the error below:

```
  • Installing fastdup (1.42): Failed

  RuntimeError

  Unable to find installation candidates for fastdup (1.42)
```

**Comment by dbickson** [comment]
HI @jdonini please give us more information, which operating system, which python, did you upgrade pip, what is the output of `pip debug --verbose` on your system

**Comment by jdonini** [comment]
Sorry about my delay, I using Python 3.11.5, and pip 23.2.1. 

The output of the Poetry is:

![2023-10-18_09-36](https://github.com/visual-layer/fastdup/assets/8041151/fb542575-74fd-47dd-8bfc-3b32969addc3)

**Comment by dnth** [comment]
@jdonini , I think we don't have support for Python 3.11 yet. Can you try changing your Python version to 3.10?

**Comment by jdonini** [comment]
It works when I change my local Python version using Pyenv to 3.10. If I use a global Python version (3.11.5), I get the same error, but in general, it works. Thanks.
