### ISSUE TITLE
Add informative error messages for failures

### ISSUE THREAD

**Issue by amirmk89** [visual-layer/fastdup#88]
When running on a few images and no clusters are found, fastdup fails with a non-informative error:

```
FastDup Software, (C) copyright 2022 Dr. Amir Alush and Dr. Danny Bickson.
2023-03-06 16:50:54 [INFO] Version 0.213 Release compiled on Mar  5 2023 22:01:56
2023-03-06 16:50:55 [DEBUG] Read model file UndisclosedFastdupModel.ort input layer name input output layer name global_average_pooling2d_12
2023-03-06 16:50:55 [DEBUG] out_dims[0] = -1
2023-03-06 16:50:55 [DEBUG] out_dims[1] = 576
2023-03-06 16:50:55 [DEBUG] Model dimensions are -1 224 224 3 is_nchw? 0 is b/w? 0
2023-03-06 16:50:55 [INFO] Going to loop over dir /Users/luca/.active_learning/cache/817cacfa24019f899177c646d1ac622d
2023-03-06 16:50:55 [DEBUG] find -L /Users/luca/.active_learning/cache/817cacfa24019f899177c646d1ac622d -type f | egrep -i '\.bmp$|\.jpg$|\.tiff$|\.giff$|\.jpeg$|\.png$|\.tif$|\.tar$|\.tar.gz$|\.zip$|\.tgz$|\.mp4$|\.avi$|\.heif$|\.heic$'| sort > /Users/luca/.active_learning/cache/817cacfa24019f899177c646d1ac622d/fastdup2/tmp/files0.txt
2023-03-06 16:50:55 [DEBUG] Read a total of 7 lines from /Users/luca/.active_learning/cache/817cacfa24019f899177c646d1ac622d/fastdup2/tmp/files0.txt
2023-03-06 16:50:55 [DEBUG] Total images read so far 7
2023-03-06 16:50:55 [INFO] Found total 7 images to run on
2023-03-06 16:50:55 [DEBUG] Going to init pool
2023-03-06 16:50:55 [DEBUG] Starting to run with 10 threads
2023-03-06 16:50:55 [DEBUG] Going to init quad array of size 7
2023-03-06 16:50:55 [DEBUG] Going to init jobs
2023-03-06 16:50:55 [DEBUG] Run inference /Users/luca/.active_learning/cache/817cacfa24019f899177c646d1ac622d/e6ac1147c820700835f393a072b9352a_ca6ec33a91


0 :[155.0000, 162.0000, 178.0000, 157.0000, 164.0000, 180.0000, 156.0000, 163.0000, 179.0000, 156.0000]
2023-03-06 16:50:55 [DEBUG] Image load and resize took 8 from /Users/luca/.active_learning/cache/817cacfa24019f899177c646d1ac622d/e6ac1147c820700835f393a072b9352a_ca6ec33a91558919fa11fb96f1c3c371.jpg
...

2023-03-06 16:50:56 [DEBUG] Wrote total of 7 stats
2023-03-06 16:50:56 [DEBUG] Done store results
2023-03-06 16:50:56 [INFO] Found total 7 images to run on
2023-03-06 16:50:56 [DEBUG] Going to init quad array of size 1000
2023-03-06 16:50:56 [DEBUG] Going to run 1 batches with reminder 7
2023-03-06 16:50:56 [DEBUG] Going to run single thread normalization of 7 from offet 0
2023-03-06 16:50:56 [DEBUG] Finished normalization
after normalization10 :[0.0693, 0.0723, 0.0178, 0.0703]
2023-03-06 16:50:56 [DEBUG] 1) Going to train NN model. Train sample factor 1.000000 howmany 7
2023-03-06 16:50:56 [DEBUG] 1) Finished train() NN model
2023-03-06 16:50:56 [DEBUG] 1) Finished add() NN model
2023-03-06 16:50:56 [DEBUG] Total data points added= 7
2023-03-06 16:50:56 [INFO] 2) Finished write_index() NN model
2023-03-06 16:50:56 [INFO] Stored nn model index file /Users/luca/.active_learning/cache/817cacfa24019f899177c646d1ac622d/fastdup2/nnf.index
2023-03-06 16:50:56 [DEBUG] 3) Finished search() NN model
2023-03-06 16:50:56 [DEBUG] KNN results
    0 : 1.00000     1 : 0.75306     5 : 0.71235 
    1 : 1.00000     4 : 0.76092     0 : 0.75306 
    2 : 1.00000     3 : 0.66824     4 : 0.65750 
    3 : 1.00000     0 : 0.69905     2 : 0.66824 
    4 : 1.00000     1 : 0.76092     0 : 0.66243 
    5 : 1.00000     0 : 0.71235     6 : 0.66099 
    6 : 1.00000     5 : 0.66099     3 : 0.64670 
2023-03-06 16:50:56 [DEBUG] Found total results  14
2023-03-06 16:50:56 [DEBUG] Replacing lower threshold 0.050000 with position 13 top_k.size() 14 loc pos: 0.646702 last pos: 0.646702 0.950000 13.300000
2023-03-06 16:50:56 [INFO] Total time took 1010 ms
2023-03-06 16:50:56 [INFO] Found a total of 0 fully identical images (d>0.990), which are 0.00 %
2023-03-06 16:50:56 [INFO] Found a total of 0 nearly identical images(d>0.980), which are 0.00 %
2023-03-06 16:50:56 [INFO] Found a total of 0 above threshold images (d>0.900), which are 0.00 %
2023-03-06 16:50:56 [INFO] Found a total of 1 outlier images         (d<0.050), which are 4.76 %
2023-03-06 16:50:56 [INFO] Min distance found 0.647 max distance 0.761
2023-03-06 16:50:56 [INFO] 

Example similar files
from,to,distance
2023-03-06 16:50:56 [INFO] Running connected components for ccthreshold 0.900000 
2023-03-06 16:50:56 [DEBUG] 14 After removing edges removed 14 edges h 0
.02023-03-06 16:50:56 [DEBUG] Last component id was 7
2023-03-06 16:50:56 [DEBUG] Total component stats size is 7 last component was 7
2023-03-06 16:50:56 [DEBUG] Going to store components to file /Users/luca/.active_learning/cache/817cacfa24019f899177c646d1ac622d/fastdup2/connected_components.csv
Traceback (most recent call last):
  File "/Users/luca/opt/anaconda3/envs/al/lib/python3.8/site-packages/fastdup/sentry.py", line 114, in inner_function
    ret = func(*args, **kwargs)
  File "/Users/luca/opt/anaconda3/envs/al/lib/python3.8/site-packages/fastdup/fastdup_controller.py", line 259, in connected_components
    assert df_info is not None and not df_info.empty, f"Missing file {FD.CC_INFO_CSV}"
AssertionError: Missing file component_info.csv

**Comment by dbickson** [comment]
Should be fixed in 0.905
